### PR TITLE
Move state management out of the EVM

### PR DESCRIPTION
**Pull request by masonforest**
State management is now all done all through `AccountInterface`. In
`MockAccountInterface` we implement storage as as Map. When connecting
to the blockchain we can implement `AccountInterface` to read and write
 to and from the `Trie.`

### CODE REVIEW

**Comment by hayesgm** [comment]
So, I'm not convinced we can move state out entirely. More, we can ignore what it means and pass it around to other functions. E.g. the previous `Blockchain.Interface.AccountInterface` implements:

```elixir
@spec get_account_balance(EVM.Interface.AccountInterface.t, EVM.state, EVM.address) :: nil | EVM.Wei.t
  def get_account_balance(_account_interface, state, address) do
    case Blockchain.Account.get_account(state, address) do
      nil -> nil
      account -> account.balance
    end
  end
```

There's no obvious way to execute that function without being given the current state.  Theoretically, we could store state in `Blockchain.Interface.AccountInterface` when we initialize it, but the state changes throughout a message call (and in ways that aren't necessarily obvious to the interfaces), so it's likely we'd determine the wrong value if we stored it there. E.g. what is `ContractInterface` changes state then we call `AccountInterface` in the same execution, does it have the updated state?

What I am proposing is that we keep state in the EVM, but we largely treat it as an opaque value to be passed to other functions that care more about it. E.g.

`@spec get_storage(t, EVM.address, EVM.val) :: EVM.val` becomes `@spec get_storage(t, EVM.state, EVM.address, EVM.val) :: EVM.val`

`@spec suicide_account(t, EVM.address) :: t` becomes `@spec suicide_account(t, EVM.state, EVM.address) :: {t, EVM.state}`

etc...

**Comment by masonforest** [comment]
Gotchya, valid points.

So yeah, originally I thought we'd store state on `Blockchain.Interface.AccountInterface` or `Blockchain.Account` but instead of storing state directly we'd store a reference to the db:

Then your `get_account_balance` could look like this.


    Blockchain.Interface.AccountInterface do
        defstruct [
            db: nil
        ]

      @spec get_account_balance(EVM.Interface.AccountInterface.t, EVM.state, EVM.address) :: nil | EVM.Wei.t
      def get_account_balance(account_interface, state, address) do
        case Blockchain.Account.get_account(account_interface.db, address) do
          nil -> nil
          account -> account.balance
        end
      end
    end

Obviously you might need to update `Blockchain.Account.get_account` as well. Alternatively you could store the `db` instance on `Account` and store references to the accounts on the interface.
 
Your `ContractInterface` interface could use the same db to keep that in sync as well.

My goal here is to eliminate passing the state around in the EVM. If we can make the EVM stateless and only pass in a stateful interface I think that'd simplify the code quite a bit. Ideally the EVM doesn't even know what a MerklePatriciaTree is and we can remove the dependency all-together!  😀 LMK what you think...


As a side note: We might also consider merging the `AccountInterface` and the `ContractInterface` I'm pretty sure a contract is just and account that has a `:code` value.

**Comment by hayesgm** [comment]
One important thing to remember is that "state" is really just a glorified hash value. The idea is that all operations that affect state return a new root of a MerklePatriciaTrie that has the given value encoded in it, somewhere.

The primary concern is thus that one "state operation" operation affects any other operation that may touch that trie. I'm concerned, for instance, is there were introduced a "SWAP_ACCOUNT_BALANCES" function (though, CALL may be sufficient for this example). Then we'd have something like this:

```
# In Blockchain App
account_a = AccountInterface{address: a, state: state_1}
account_b = AccountInterface{address: b, state: state_1}

# in EVM
func swap_balances(acct_a, acct_b):
  a_balance = AccountInterface.get_balance(acct_a)
  b_blaance = AccountInterface.get_balance(acct_b)

  AccountInterface.update_acct_balance(acct_a, b_balance)
  AccountInterface.update_acct_balance(acct_b, a_balance)

# After function call in Blockchain app
updated_account_a = AccountInterface{address: a, state: state_2}
updated_account_b = AccountInterface{address: b, state: state_3}
```

The concern is we have two final states, since both operations affected a state and didn't reflect that in the other. `state_2` (a hash) is the root of a trie where a's balance is updated, but not b's. `state_3` is the root of a trie where b's balance is updated, but not a's.

Previously, we had:

```
func swap_balances(state, acct_a, acct_b):
  a_balance = AccountInterface.get_balance(state, acct_a)
  b_blaance = AccountInterface.get_balance(state, acct_b)

  updated_state =
    state
    |> AccountInterface.update_acct_balance(acct_a, b_balance)
    |> AccountInterface.update_acct_balance(acct_b, a_balance)
```

That final `updated_state` is the hash of a trie which both a's updated balance and b's. This is the state that we store (assuming successful operation) and pass to the next run of the EVM.

I think you may be suggesting instead of passing around state, we make each object encode state in it (which would be difficult if we have multiple interfaces, plus the interfaces aren't really meant to carry state). We could do it, but then I'd suggest we create a new state interface that itself could be passed around instead of embedding it in the Account or Contract interface, but then we're right back where we started, I think.

But, maybe if we merge Account and Contract interface, we could make this work? I don't think we could make it work with having more than a single interface that ever needs to touch state...

**Comment by masonforest** [comment]
Yep, we wouldn't have separate states for separate accounts. There would just one state container that would contain the state of all the accounts.

So from your example we would have:

    func swap_balances(account_interface, acct_a, acct_b):
      a_balance = AccountInterface.get_balance(account_interface.db, acct_a)
      b_balance = AccountInterface.get_balance(account_interface.db, acct_b)

      updated_state =
        account_interface.db
        |> AccountInterface.update_acct_balance(acct_a, b_balance)
        |> AccountInterface.update_acct_balance(acct_b, a_balance)

(or something of the likes)

> which would be difficult if we have multiple interfaces,

I think it'll work if both interfaces are hitting the same backend db. I agree this would probably be confusing so we should probably merge them into one interface.

> plus the interfaces aren't really meant to carry state

Agreed, interfaces aren't meant to carry state but their implementations can. That way we can swap out different state implementations without changing the EVM. Say for example we want to use `rocksdb` instead of `leveldb` (which I think we might want to try!). If we could change that in an interface then we wouldn't have to change it in the EVM.


I'm not a fan going one way because the work is already done. If we really think the right way to do this is to keep state a concern or the EVM we can close this PR and carry on. The way I think about it though, is a VM shouldn't care what it's storage backend is. It should just be pushing bytes around... 
 

LMK what you think :)

**Comment by hayesgm** [comment]
I'll give this a go and see how it works out. Report back soon.

**Pull request merged**
